# Generated by Django 3.2.22 on 2023-11-21 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='herbariumFolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='herbariumImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbaLook_app.herbariumfolders')),
            ],
        ),
    ]
